# Generated by Django 3.1.1 on 2020-09-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=150),
        ),
    ]
